"""Initial migration

Revision ID: d78d5a73d2f2
Revises:
Create Date: 2025-03-07 19:32:29.336829

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d78d5a73d2f2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
