services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/auth_db
    volumes:
      - .:/src
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5557:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]
